spring.application.name=GatewayService
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


spring.cloud.gateway.server.webflux.routes[0].id=BookModule
spring.cloud.gateway.server.webflux.routes[0].uri=lb://lms2
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/book/**


spring.cloud.gateway.server.webflux.routes[1].id=UserModule
spring.cloud.gateway.server.webflux.routes[1].uri=lb://UserManagementService
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[2].id=orderModule
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ordermanagement
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/order/**